import Head from "next/head";
import { getAuth } from "firebase/auth";
import { firebaseApp } from "@/firebase";
import { useSignInWithGoogle } from "react-firebase-hooks/auth";

const auth = getAuth(firebaseApp);

export default function Home() {
  const [signInWithGoogle, user, loading, error] = useSignInWithGoogle(auth);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="btn" onClick={() => signInWithGoogle()}>Sign in</button>
      </main>
    </>
  );
}
